name: Build & Publish Gatsby to Cloudflare Workers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      sitedir: ./site

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --cwd ${{env.sitedir}}
        name: Install dependencies

      - run: yarn build --log-pages --cwd ${{env.sitedir}}
        name: Build
        env:
          NODE_ENV: production

      - run: ls -lart ./public && echo ${{github.ref}}
        working-directory: ${{env.sitedir}}
        name: Check output files
