name: Build & Publish Gatsby to Cloudflare Workers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      site-directory: ./site

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd ${{env.site-directory}} install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd ${{env.site-directory}} build
    - name: Run simple echo command
      run: ls /public
      working-directory: ${{env.site}}
